language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
# Send coverage data to Coveralls
after_script: "cat ./coverage/coveralls/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
